name = "red"
license = "MIT"
licenselink = "https://github.com/Chapien/blue/raw/refs/heads/main/LICENSE"
description = "Custom Hugo theme based on redstrate.com"
homepage = "https://github.com/Chapien/blue"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Claire <claire@chapien.net>"
  homepage = "https://chapien.net/"
